name: Eink Display Web Build

on:
  push:
    paths:
      - "eink-display-web/**"
  pull_request:
    paths:
      - "eink-display-web/**"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      epd-index: ${{ steps.html.outputs.epd_index }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"
          cache-dependency-path: eink-display-web/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: eink-display-web

      - name: Build
        run: pnpm run build
        working-directory: eink-display-web
        env:
          VITE_GRAPHQL_API_KEY: ${{ secrets.HOME_GATEWAY_API_SECRET }}

      - name: Output html
        id: html
        run: echo "epd_index=$(cat ./dist/index.html)" >> "$GITHUB_OUTPUT"

  upload-object:
    needs: [build]
    uses: Accurate0/workflows/.github/workflows/upload-object.yaml@main
    with:
      namespace: "home-gateway"
      object-name: "index.html"
      object-content: ${{ jobs.build.outputs.epd-index }}
    secrets:
      KEY_ID: ${{ secrets.OBJECT_REGISTRY_GHA_KEY_ID }}
      PRIVATE_KEY: ${{ secrets.OBJECT_REGISTRY_GHA_PRIVATE_KEY }}
